### ISSUE TITLE
Mining Modules

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#105]
**Is your feature request related to a problem? Please describe.**
Its annoying to have to go to your ship every time you run out of battery.

**Describe the solution you'd like**
Mining Modules. Not modules that mine for you, modules with specific slots that store mining equipment and have storage in them. Have to read the post to get the full idea. 

**Describe alternatives you've considered**
None.

**Additional context**
Full post is at https://steamcommunity.com/app/588210/discussions/1/1697167355228276591/

**Comment by GuiltyNeko** [comment]
Summary: Mining Modules. Not modules that mine for you, modules with specific slots that store mining equipment and have storage in them. Have to read the post to get the full idea. [https://steamcommunity.com/app/588210/discussions/1/1697167355228276591/](url)

**Comment by CheeseJedi** [comment]
This sounds like it has a _lot_ of overlap with an Arges with it's cargo bay + terminal, storage shelves, battery charger.

**Comment by zorkind** [comment]
Yeah, also the battery limit is set in place so you have some kind of "slow down" on mining, if we make mining super easy, the game loses it's 1 and only gate towards free building / sandbox spawn commands :-\
