### ISSUE TITLE
0 resources remaining after transfer

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#11]
**Describe the bug**
When dragging resources from one container into another, a ZERO amount remains listed in the origin.

**To Reproduce**
1. Access any cargo panel in FAB / OP / CBM
2. Drag any material from one container, to another, it can be in the same module or into another or into a sub-system.
3. Select the entire amount.

**Expected behavior**
Nothing of that material should remain in the source.

**Screenshots**
None provided.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
Sounds like a floating point rounding issue: a transfer leaves behind a fractional amount of material in the source inventory, which when rounded down for UI display, results in a zero amount being displayed.

Perhaps the issue lives in how the inventory item transfers are handled? - I've not looked in to this too much, but it frequently happens in the original game, and fixing this would be a nice quality-of-life improvement.
