### ISSUE TITLE
Make it so that Stimpacks work like SmallCanisters so "healing points" are not wasted.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#134]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If a Stimpck heals 25hp, but I want to top off at 80/100hp before a fight. I still have a stim with 5/25 healing left

**Describe alternatives you've considered**
Nope.

**Additional context**
Nope.

**Comment by zorkind** [comment]
Rejecting this for now, the stims are meant to be consumables, not canisters.

Altho i agree the amount of heal is not ideal and you don't have the faintest idea of how much it heals, turn it into a canister is not the solution :)
