### ISSUE TITLE
T3 and T4 for ASAT scanners, as well as... make them useful?

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#137]
**Is your feature request related to a problem? Please describe.**
Its annoying for it to show the symbols and not names of materials, and then how many of all resources are present on the asteroid.

**Describe the solution you'd like**
Add T3 and T4 scanners that finds the general location of deposits and that finds the exact location of deposits respectively.

**Describe alternatives you've considered**
AR glasses for replacing ASAT scanners, that are built into the helmet.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
The ASAT scanners, for those who haven't used them, scan an asteroid and, at tier 1, show the icons of the resources on the asteroid (for that, just use Hellion Buddy) and at tier 2, how much of the resources are present on an asteroid. They don't show anything relating to where resources are at on the asteroid, meaning you still have to manually search the entire asteroid for the resources. A tier 3 or 4 would have some feature that helps with finding the resources.

**Comment by zorkind** [comment]
I want to change drastically how mining works for 0.1.0 but i am not sure if i will have time to do this.

AR glasses is too much imo, we can further discuss this, but i am rejecting for now.
