### ISSUE TITLE
Another light in the arges cargo bay for the part that's in shadow near the outer door.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#140]
**Is your feature request related to a problem? Please describe.**
Kind of. Unable to see items without light, which is annoying.

**Describe the solution you'd like**
Add a light, even a invisible one.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
![picture](https://i.imgur.com/rWcU38A.png)
The corner shown in this picture can end up extremely dark, making it difficult or impossible to see what's there.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/92346921-b2020100-f0a4-11ea-8815-ff334199ef40.png)
![image](https://user-images.githubusercontent.com/11562921/92346936-c1814a00-f0a4-11ea-8e03-c31c795c7085.png)
