### ISSUE TITLE
SOE start corridor misalignment

### ISSUE THREAD

**Issue by GuiltyNeko** [zorkind/Hellion-Rescue-Project#142]
**Describe the bug**
The CTM and a custom module don't match up where it looks like they ought to, since the module has a docking port-like adapter.

**To Reproduce**
1. Start a new game using the SOE Start option
2. Go out into the CTM
3. The docking door B will be blocked by another module.

**Expected behavior**
The special SOE module has an AltCorp-style docking mount on the side that looks as though it ought to be docked squarely to the CTM with.

**Screenshots**
![picture](https://i.imgur.com/R2ryaaO.png)
![picture](https://i.imgur.com/EM5JROh.png)

**Additional context**
None.

**Comment by GTink911** [comment]
Can you please verify that they are docked together by trying to undock or trying to push the module?

**Comment by GuiltyNeko** [comment]
When pulling the undock lever, they undock, but I'm unable to re-dock them using the docking panel, since it's a starting station. So yes, they're docked together, they just start aligned wrongly.

**Comment by GuiltyNeko** [comment]
When looking in the server files, the spawn4 file in the stations folder specifies which modules are connected to which through which ports. There's nothing about exact positioning, and it looks like you could even make stations that spawn with modules inside each other with this, but not station with modules physically distanced from each other but still connected. Or in other words, the docking point on the SOE module isn't the same between the code and the model.

**Comment by zorkind** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/11562921/91374418-8c484280-e7ee-11ea-8760-37229c660919.png)
