### ISSUE TITLE
Larger fabricator with bulk crafting and another exit.

### ISSUE THREAD

**Issue by TZNR316** [zorkind/Hellion-Rescue-Project#145]
An exit on the other side of the fabricator

**Comment by GuiltyNeko** [comment]
Perhaps a second, larger fabricator instead? Could perhaps combine with #62 to have a larger fabricator with multiple exits that can also do the bulk crafting. Just keep the current one how it is and make a larger better one.

**Comment by TZNR316** [comment]
Great idea!

**Comment by GTink911** [comment]
Merged.

**Comment by GTink911** [comment]
Only be able to craft custom station modules in a large fabricator?

**Comment by TZNR316** [comment]
i think that fabricator should also have multiple shredders and scanners
because there usfull when with friends

**Comment by TZNR316** [comment]
oh and maybe something like a "craft card" wich saves recipies

**Comment by zorkind** [comment]
In 0.2.0 this will be reworked, rejecting for now.
