### ISSUE TITLE
Ghost version of myself in front of me preventing me from getting to the RCS controls on the T corridor.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#147]
**Describe the bug**
A ghost version of myself appears in front of me. It moves with me forwards, backwards, and left to right. It did not move forward as I could not move in that direction.

**To Reproduce**
1. Go to SoE or RA start.
2. Move outside.
3. See error
(Only seen once, cannot reproduce.)

**Expected behavior**
No ghost.

**Screenshots**
None.

**Additional context**
Possibly caused by camera moving backwards from body.

**Comment by zorkind** [comment]
No details, no description.

**Comment by GuiltyNeko** [comment]
Showed up after I left the SOE start on my HRP server. A ghost version with no suit appeared from somewhere and prevented me from going forwards at all. Moved with me, including when I went backwards. Only thing it didn't copy was forward movement, which it physically blocked. Had my username.

**Comment by GuiltyNeko** [comment]
Not specific to the SOE start, happened with the RA start as well.
