### ISSUE TITLE
SoE start, station disappearing.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#149]
**Describe the bug**
The whole station disappeared when i got out of it.

**To Reproduce**
1. Start a new game using the SOE Start option.
2. EVA out of it.
3. See error

**Expected behavior**
The station should remain close to the player.

**Screenshots**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
I was not able to reproduce this in HRP.
:(
