### ISSUE TITLE
Make the Bridge turret in Arges higher

### ISSUE THREAD

**Issue by TZNR316** [zorkind/Hellion-Rescue-Project#154]
**Is your feature request related to a problem? Please describe.**
Yes, perhaps it was not noticed by the devs, but when the turret is deployed inside the ARGES top deck, the turret will hit your head.

**Describe the solution you'd like**
Perhaps changing the scale of the turret for only this, or move the slot a bit up.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GTink911** [comment]
My bad. Also would likely distort turret module.

**Comment by GuiltyNeko** [comment]
With the turret in its current location, you can be standing near to it and it'll swivel around to bump into you, which, if you're in your inventory, will cause you to float off, which is an unrelated issue, but makes putting things into the lockers or taking them out difficult.

**Comment by zorkind** [comment]
Fixed.

Some pipes in the ceiling where removed, i think they wont be missed, some screen shots of how it looks, the height is the same as the door frame as you can see in the picture.

![image](https://user-images.githubusercontent.com/11562921/89704069-50c10380-d927-11ea-9009-5ed18480128b.png)

![image](https://user-images.githubusercontent.com/11562921/89704085-7d751b00-d927-11ea-94dc-8db24bd456f3.png)


It was like this before:
![image](https://user-images.githubusercontent.com/11562921/89704087-87971980-d927-11ea-983a-452ffbe8845c.png)
