### ISSUE TITLE
Small tugboat-like ship

### ISSUE THREAD

**Issue by GuiltyNeko** [zorkind/Hellion-Rescue-Project#174]
**Is your feature request related to a problem? Please describe.**
Somewhat. The rotation of stations can be a bit tricky to cancel out, as it can be tricky to even dock to a station in the first place when it's rotating.

**Describe the solution you'd like**
A small, cheap ship with an anchor and engines that exists just to move from one place to another and stop the rotation of derelict stations. Would be smaller than the steropes, and as small as possible even. Would lack an interior, just having an open seat.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GTink911** [comment]
Stations auto stabilize after some time, assuming they have RCS fuel in them. Unless it has bugged in this release, this is still the case and is not at this time going to be changed.
