### ISSUE TITLE
The servers...

### ISSUE THREAD

**Issue by TZNR316** [zorkind/Hellion-Rescue-Project#180]
**Describe the bug**
Its like thaT: in **every** server i and my friend connects we get 300 pings and disconnects too
**To Reproduce**
1. go to multiplayer'
2. Click on a server
3. click connect
4. see urself
**Expected behavior**
Playing in a server
**Screenshots**
uh no
**Additional context**
.

**Comment by zorkind** [comment]
This is an old task about the servers and it no longer represent the current status of the servers.
