### ISSUE TITLE
Slot size revision

### ISSUE THREAD

**Issue by GuiltyNeko** [zorkind/Hellion-Rescue-Project#182]
**Is your feature request related to a problem? Please describe.**
Some items have slot sizes that don't make sense, or can't be placed on shelves at all.

**Describe the solution you'd like**
An overall review of the slot sizes of all items to change them to sizes that make more sense for the visual size of the item. 
#51 is an example.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
I have made changes into this, it is now allowed to be added pictures and posters in medium and small shelves.
Also small resource containers can be fitted into small shelfs.

Please if there's anything else you feel that should be in the shelfs, let me know, and i reopen this issue, for now i will close.
