### ISSUE TITLE
Injector in the LSM

### ISSUE THREAD

**Issue by Hindolur** [zorkind/Hellion-Rescue-Project#192]
**Describe the bug**
the injector in the LSM can only be put in by proxy looting. In the normal hellion it would often fall out or become missing.
**To Reproduce**
1. Go to panel try to insert the injector using the F button
2. hit tab to show proximity loot. able to insert the injector

**Expected behavior**
be able to insert the injector in using the F button

**Screenshots**
was unable to get a screen shot showing the injector sticking out.

**Additional context**

**Comment by zorkind** [comment]
I am sorry but i can't reproduce this in HRP, perhaps i have fixed this when i worked on the loot thro wall bug.

If you can reproduce this in HRP, let me know.
