### ISSUE TITLE
Fabricator-specific blueprints

### ISSUE THREAD

**Issue by GuiltyNeko** [zorkind/Hellion-Rescue-Project#195]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make blueprints specific to each fabricator module, instead of the player. 

**Describe alternatives you've considered**
None.

**Additional context**
Requested by @GTink911

**Comment by zorkind** [comment]
This idea is already in alignment with the database gameplay for 0.2.0 it will be a portable "pendrive" if you will, this will be further developed and thought thro wen the time comes, but not for 0.1.0 tho, at least not for now.
