### ISSUE TITLE
Warp Interdiction 

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#198]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A way to forcibly pull other players and NPC ships out of warp. Even pull players out of interstellar warp once the Tamara roles around.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
Not for now, warping is the 1 safe place players have for now.

Perhaps we can re-think this later on, for now rejecting :)
