### ISSUE TITLE
Fit Steropes airlock screen to the entire panel

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#2]
**Describe the bug**
The airlock panels are smaller than the borders of the panel.

**To Reproduce**
1. Go to the Steropes Air-lock
2. Look at the air-lock panel
3. See error

**Expected behavior**
The green background of the panel should cover the entire surface of the panel.

**Screenshots**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
Fixed, here is how it looks now:
![image](https://user-images.githubusercontent.com/11562921/89704197-376c8700-d928-11ea-9b8b-25304e103180.png)

This also was fixed for the security panel and all other panels in CECA.
