### ISSUE TITLE
Rename Haven to Outpost

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#210]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Rename the Haven module to Outpost. As always, can be toggled.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
I'm not sure why the starter scene Outpost module was renamed to Haven in the first place. Perhaps it was so it had a unique name so new players don't mis-identify and confuse some random thing that has an Outpost attached? Unsure.

Are other Outpost modules correctly named as Outposts when they spawn with other modules, or were they _all_ renamed?

**Comment by zorkind** [comment]
This has been done, but since this is in Server side and in json files, no toggle will be added, server Admins can switch it back by editing the json file 👍
