### ISSUE TITLE
Turret lights go through walls

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#217]
**Describe the bug**
Turret lights penetrate through walls

**To Reproduce**
1. Place a turret on a slot
2. View lighting sometimes penetrating. 

**Expected behavior**
Lights should stop at the wall.

**Screenshots**
None.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
Non shadow casting lights (lights that do not take in to account colliders or other geometry, relying only on the intensity setting) are significantly cheaper (particularly if baked) - in the final state of the original game there are only a small number of shadow-casting lights (that take in to account geometry) per module, and probably for a very good reason.

The total number of lights in ships/modules are fixed, making them good candidates for various optimisiation techniques, and were presumably tweaked significantly (using area lights/baking where possible) by ZG to reduce performance budget requirements on the client.

I guess my question here is:  Will making the turret light source (of which there could be quite a few per scene in different situations) _more expensive_ be worth it for game-play reasons?

Sure you can perhaps tell the tier of a turret through a wall (or even that there's a turret there) - if that's the concern, would removing their light source be a better option?

Game development is often _full_ of compromises. I personally never had an issue with turret lights shining through walls, especially knowing why this happens,  and I suspect there may be better places to spend the limited performance budget. But that's just me. :)

**Comment by zorkind** [comment]
This can potentially be already fixed by the changes made in the turret lights, need to be tested.

**Comment by GuiltyNeko** [comment]
Might be able to reduce the occurrences of turret lights through walls significantly by only showing them in modules with an exit to space, or when you are in a module connected to a module with a turret, or in that module. Basically, module-proximity based. If you're looking at an OUTP that's 5 modules away from an exit to space, there's no harm in not being able to see the light until you're in a position to do something about the turret. And other things should be similarly occluded as well.

**Comment by zorkind** [comment]
From what i could test, this issue has been resolved by reducing the amount of light generated by the turrets.

If any specific spots are found leaking, please reopen this task with the proper screen shot and description of the location.
