### ISSUE TITLE
Cinematic tools

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#218]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Cinematic tools like orbit, 3rd person, etc. Can be enabled/disabled in server settings, or allow only server admins to use them.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
I much prefer the way the game is now without third-person, and I'd like to keep it that way, so maybe third person is an admin-only thing, or something. Probably the same with any other camera-manipulating tools too.

**Comment by GTink911** [comment]
Edited.

**Comment by CheeseJedi** [comment]
This kind of idea had been put to ZG on a few occasions - they had suggested creating a helmet variant with no UI or distortions/overlay/etc for creating cinematics with although as far as I'm aware it never made it in to the game.

**Comment by GTink911** [comment]
Apparently there's a screenshot mode activated by F10, so that partially fits these requirements.
