### ISSUE TITLE
Cargo boxes can be crafted

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#22]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Allow crafting of the cargo boxes.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
This has been fixed in Issue https://github.com/zorkind/Hellion-Rescue-Project/issues/302
