### ISSUE TITLE
Arges ladder detach into airlock keeps jetpack off

### ISSUE THREAD

**Issue by zorkind** [zorkind/Hellion-Rescue-Project#222]
**Describe the bug**
When you use the Arges ladder into the airlock the jetpack don't turn on like it happens in the AIM module.

**To Reproduce**
1. Go to the Arges
2. Climb the ladder into the ailock
3. If you have a proper jetpack equipped and fueled, it should turn on when you detach from ladder into zero G.

**Expected behavior**
If you have a proper jetpack equipped and fueled, it should turn on when you detach from ladder into zero G.

**Screenshots**
None

**Additional context**
None.

**Comment by codemonger** [comment]
When this occurs its as if the game thinks you're without a jetpack and can maneuver up to 1.0m/s (using handrails in interiors with no jetpack).

One workaround often works is to spacewalk into the Steropes airlock, go inside the cabin, then leave again.  Jetpack functionality is often restored.

However, I've also encountered this same issue only once from login into cryo of the CQM then float through a CSM while holding a fueled jetpack in hands.  Exiting the CSM into a long corridor to an AM.  Then going into space the jetpack is broken.

**Comment by zorkind** [comment]
this bug has already been fixed, it's done since august.
