### ISSUE TITLE
Remove ability to pressurize vents in the LSM

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#235]
**Describe the bug**
The ability to pressurize vents in the LSM. Useless because it pressurizes the room as well.

**To Reproduce**
1. Go to life support menu
2. Scroll down to LSM
3. See error

**Expected behavior**
Only be able to pressurize rooms

**Screenshots**
None.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
I think this is related to an omission on ZGs part when the life support re-work happened.

The vents show up as controllable areas, even though they are technically supposed to be part of the attached room (and not shown as a separate area in the LS panel).

The vent covers that separate the room and it's vent(s) are clearly not intended to look air-tight, so there seems to be no good reason to have these cluttering the UI, or being separately pressurisable.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/95666676-51963180-0b32-11eb-9371-a498d18d7ba4.png)
