### ISSUE TITLE
Refine air into oxygen and nitrogen

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#236]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Conversion of air into oxygen and nitrogen minus about half of resources.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
You can already do this by putting air into the CBM/haven refinery.
