### ISSUE TITLE
Fabricator canister shelf sets canisters backwards

### ISSUE THREAD

**Issue by codemonger** [zorkind/Hellion-Rescue-Project#243]
**Vanilla / HRP**
Vanilla.

**Client Version**
0.5.2 (Vanilla)

**Describe the bug**
In the Fabricator room walking past the computer console screen on the left and rounding the corner, there is a pair of shelves on the right side that hold canisters.  On both shelves, upper and lower, whenever a canister is placed on the shelf it faces the opposite direction: the LCD status display faces toward the wall, and should be facing toward the front of the shelf so that you can read it when you walk by.  If corrected, it would be like (nearly) every other shelf that holds canisters (I haven't probably seen all the shelves in the game only getting half-way through the campaign).

**To Reproduce**
1. Go to Fabricator Module
2. Enter the room and walk into the corridor on the left
3. Face toward your right side and observe the empty shelves
4. Place a canister (empty, partially full, or full) on the shelf in one of the spaces
5. The canister faces toward the wall and the LCD screen on the canister can not be read; unlike all other canister shelves in the game.

**Expected behavior**
Each canister, both Raw and Refined Resource canisters, carry an LCD screen on one side of the canister.  This display auto-updates with the interior contents of the canister.  These displays (presumably as intended by ZG) are to be read while the canister is sitting on the shelf - because this is something the player can do with the LSM shelves and the Steropes shelves when canisters are sitting on those shelves.

Please note: the canister positioned on the top shelf on the far right end is properly oriented.  Also, the canister on the top shelf on the far left end is facing sideways - rather than forward and this could be corrected as part of this issue.

**Screenshots**
All screenshots taken from within the Fabricator Module.  The single correctly facing canister screenshot was taken from the shelves beside the Grinder.  These are **not** the shelves for which this issue is about.

![20200825182937_1](https://user-images.githubusercontent.com/4697366/91235090-c3d9c080-e702-11ea-9d89-17557e6e8589.jpg)
![20200825183310_1](https://user-images.githubusercontent.com/4697366/91235120-d48a3680-e702-11ea-9569-f51dcf80f8b0.jpg)
![20200825183400_1](https://user-images.githubusercontent.com/4697366/91235124-d6ec9080-e702-11ea-9158-857bfa63559a.jpg)

**Additional context**
Please feel free to email or PM me through GitHub if you have questions about this issue description.

**Comment by codemonger** [comment]
This issue also occurs with nearly every shelf slot in the cargo bay of the Arges.

**Comment by zorkind** [comment]
Fixed for the ones requested.
To fix for every shelf in the game, it's insane. :(

![image](https://user-images.githubusercontent.com/11562921/104374910-54be0680-5501-11eb-9ac5-80292a580bf5.png)
