### ISSUE TITLE
Show time until warp on ship screens.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#256]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Similar to the 'Arrival Time' during warp, one for 'Time Until Warp' would be helpful for coordination.

**Describe alternatives you've considered**
Show Arrival and Until Warp on HUD.

**Additional context**
None.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/104941810-4f920900-5992-11eb-9a04-af737be46592.png)
