### ISSUE TITLE
See into Arges cargo bay from warp drive room.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#270]
**Vanilla / HRP**
Vanilla.

**Client Version**
0.5.2 (Vanilla)

**Describe the bug**
You can see into the Arges cargo bay from the warp room.

**To Reproduce**
1. Go to the Arges warp room
2. Look below warp cell storage from ladder position
3. See error

**Expected behavior**
Should see a flat surface.

**Screenshots**
![image](https://user-images.githubusercontent.com/42620721/94347456-3c28ef80-ffe9-11ea-8409-f86de9f25b7e.png)

**Additional context**
None.

**Comment by zorkind** [comment]
Fixed ;)

![image](https://user-images.githubusercontent.com/11562921/95663977-1f78d580-0b1a-11eb-8246-f942df8f298c.png)

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/100523525-d21afb00-318f-11eb-9cf9-2fa509a5169d.png)
