### ISSUE TITLE
Arm Display Interface (ADI?)

### ISSUE THREAD

**Issue by JohnathanMor** [zorkind/Hellion-Rescue-Project#287]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An arm display that interfaces with your ship and station. It allows you to see the status of your ship and modules. For instance, the health, warnings, statuses, etc. While it would be cool to do things from this interface, it would deter from the roles and jobs of other members. Maybe make this an option when there are no other players assigned to your base?

**Describe alternatives you've considered**
The arm display is all I got.

**Additional context**
No.

**Comment by GuiltyNeko** [comment]
This sounds almost identical to what Interstellar Rift does. Furthermore, there's no justification for features that get removed the moment you have friends, so it only being an option if you're the only one authorized to the ship/station isn't really a good idea. If anything, I would expect another tab alongside the objectives and inventory screens, there's no reason to implement another entire _type_ of interface in Hellion for something like that.

**Comment by zorkind** [comment]
This gets close to having an AI assistant, which is not very "lore" based i guess i don't know.

xD
