### ISSUE TITLE
Fabricator holes

### ISSUE THREAD

**Issue by mb8360** [zorkind/Hellion-Rescue-Project#288]
**Vanilla / HRP**
HRP

**Client Version**
0.0.1

**Describe the bug**
Two holes located in the floor of the corridor of the fabricator.

**To Reproduce**
1. Enter fabricator corridor
2. Look at floor in places shown via screenshots

![20201025122721_1](https://user-images.githubusercontent.com/73439439/97114684-f3378a00-16bf-11eb-9a41-dda4857aaf1a.jpg)
![20201025122829_1](https://user-images.githubusercontent.com/73439439/97114685-f3d02080-16bf-11eb-9cea-dc0f811afa45.jpg)

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/104369498-491c1100-54fc-11eb-8937-c1bf33b73655.png)
