### ISSUE TITLE
Weapon does not get in aiming position some times

### ISSUE THREAD

**Issue by Huertix** [zorkind/Hellion-Rescue-Project#289]
**Vanilla / HRP**
Vanilla.

**Client Version**
0.5.2 (Vanilla) or HRP Version ex.: 0.0.1

**Describe the bug**
When getting the weapon out, somethings it gets in a lower position and it does not aim to the target

**To Reproduce**
pull out the weapong with key 1 or 2.

**Expected behavior**
IMPO it should always aim to target

**Screenshots**
![image](https://user-images.githubusercontent.com/7103499/98486883-36e1d600-2220-11eb-9e1e-956cf8764ab9.png)

![image](https://user-images.githubusercontent.com/7103499/98486898-406b3e00-2220-11eb-85ef-533dc19e4bf8.png)

https://cdn.discordapp.com/attachments/736233903949348865/775136272606953472/Hellion_weapon1.mov

**Additional context**

**Comment by GTink911** [comment]
Closed as it isn't a bug.
