### ISSUE TITLE
Emergency shutoff switch

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#30]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A E-Shutoff switch the kills all power to the room. if combined with #28 sets the lights to off.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
I don't understand the use of this button? shutting down all power in an emergency gives you what exactly? 

I just see this for pvp uses and how would we make sure only station personnel has access to this button? 

I will reject this for now until more details are given :D
