### ISSUE TITLE
Resolution and Quality presets lists showing repeated elements

### ISSUE THREAD

**Issue by UnopposedQuill** [zorkind/Hellion-Rescue-Project#306]
**Vanilla / HRP**
HRP

**Client Version**
0.1.0.5

**Describe the bug**
The quality and resolution presets in the video subtab of the settings are repeated several times.
The resolution ones are repeated two times.
The quality ones are repeated three times.

**To Reproduce**
1. Open the client.
2. Go to Settings.
3. Open the Video tab.
4. Click the Resolution List, or the Quality List.

**Expected behavior**
Each list should only have each element once.

**Screenshots**
![image](https://user-images.githubusercontent.com/22859823/104116998-4f837080-52e3-11eb-84c0-fda3b09448d6.png)
![image](https://user-images.githubusercontent.com/22859823/104117000-5316f780-52e3-11eb-8dc2-a25c894fde12.png)

**Comment by zorkind** [comment]
Fixed
