### ISSUE TITLE
Space can be seen from inside the Fabricator Module

### ISSUE THREAD

**Issue by UnopposedQuill** [zorkind/Hellion-Rescue-Project#310]
**Vanilla / HRP**
0.1.0.5

**Client Version**
0.1.0.5

**Describe the bug**
You can see the space from within the Fabricator Module

**To Reproduce**
1. Go inside a Fabricator module.
2. Go left inside the fabricator (behind the fabricator)
3. Turn left towards where the fabricator is.
4. Look down, you can see the space.

**Expected behavior**
Shouldn't be able to see any space from within.

**Screenshots**
To clarify these screenshots, I pointed a FM in a specific way so that you can see Bethyr from inside:

![20210110204918_1](https://user-images.githubusercontent.com/22859823/104143596-ca04cc80-5385-11eb-9207-5dad2747b2ba.jpg)
![20210110204922_1](https://user-images.githubusercontent.com/22859823/104143597-ca9d6300-5385-11eb-8583-a32fa15c8092.jpg)
![20210110204927_1](https://user-images.githubusercontent.com/22859823/104143598-cb35f980-5385-11eb-8ec5-f862344b3db2.jpg)
![20210110204933_1](https://user-images.githubusercontent.com/22859823/104143599-cb35f980-5385-11eb-8caf-faa901da77cc.jpg)
![20210110204940_1](https://user-images.githubusercontent.com/22859823/104143600-cb35f980-5385-11eb-9363-0898b6171dec.jpg)

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/104368567-01e15080-54fb-11eb-84b9-d8c01e5c9b8c.png)

![image](https://user-images.githubusercontent.com/11562921/104368599-0dcd1280-54fb-11eb-9766-bbcf85763ecd.png)
