### ISSUE TITLE
Add more types of raw resources and raw materials

### ISSUE THREAD

**Issue by ghost** [zorkind/Hellion-Rescue-Project#320]
**Is your feature request related to a problem? 
No**

Too unrealistic that items can be built out of so few elements/resources. 

Add more types of resources (eg. Carbon, Copper, Cobalt, Zinc, Gold, Tungsten, Vanadium, etc) to obtain more types of raw materials for building items.

The fabricator should use combinations of resources (eg. chemical reactions) to obtain other raw materials which can be used as alternatives to the current raw materials (found only by scavenging).

**Comment by zorkind** [comment]
Again, why can't you follow the Template format?

The mining gameplay will be reworked after 0.2.0 then we will think about what materials, but i am not going to deep into this.

This is not Space Engineers or NMS or Stationners.

Also the Fabricator is not a Furnace, its just a 3D printer, it can't produce raw materials by "mixing" anything.
