### ISSUE TITLE
Ships/stations sub-system components should also enable/disable functionalty

### ISSUE THREAD

**Issue by Wraithawk** [zorkind/Hellion-Rescue-Project#321]
**Is your feature request related to a problem? 
No**

Current upgrades for some sub-systems are exaggerated and optional (eg. tier 1 resource injectors cut's 50% of consumption rates).

Every sub-system (RCS, gravity, life support, ship sensors, main engine, warp engine, etc) should also have removable components that enable or disable functionality (CPU's or controller cards).

For example: the RCS system without a CPU would function, but without providing DIR or LAT speed indications.

The components should also be repairable in the fabricator.

**Comment by zorkind** [comment]
Why can't you follow the Template format? is it too hard?

**Comment by zorkind** [comment]
This is not happening in 0.1.0

**Comment by Wraithawk** [comment]
Hello,

Sorry for the misunderstanding, I recently discovered the game and it's amazing. So sad to see it was abandoned and so joyful to see someone will continue the work on something rare that tries to bring a glimpse of realism. 

Although, the game still has quite a few bugs, for example: sometimes, end of pressurization sound continuously until a game is reloaded or also sometimes, unable to select any orbiting object from nav mode (key 2) until you delete the ZeroGravity folder from C:\Users\...\AppData\LocalLow\ (the solve was for the problem of new mission objective not triggering after previous mission accomplished).
As I understand, the template for v0.1.0 is found in the roadmap?

If it's not too much to ask, is there a plan to make the systems require parts in order to function like it was before the Kessler Update? That would make more sense for the importance of the parts.
