### ISSUE TITLE
Passive RADAR or active RADAR

### ISSUE THREAD

**Issue by Quarkof** [zorkind/Hellion-Rescue-Project#325]
**Is your feature request related to a problem? Please describe.**
No

Select if a ship's RADAR is passive (non-illuminating) or active (illuminating). 

Passive ship can see others ship "illuminating" active RADAR. Active ship can see all other "illuminated" ships. Two ships with passive radar can find each other only visually. Passive RADAR cannot see structures.

RADAR tier enhancements improve also active RADAR range.

**Comment by zorkind** [comment]
This idea is part of a bigger idea I have discussed publicly some time ago about a "Fog of War" in the NavMap, which will not allow you to see objects far away, even with scanners, you can only get estimates, unless you hack a satellite and download a map of current objects positions, this map will be an aproximation ofc, based on the time the map was generated, objects orbits might shift in various ways and their position might not be the same when you travel to said object.

But that is for big distances, for 1000km and bellow, your idea takes place with active scanning, passive scan is aprox. 10km only.

**Comment by Quarkof** [comment]
So does this mean, you are considering the active/passive idea under 1000km? :)

Would be great to be able to hide being an asteroid against visual sight or why not, an Infra Red scanner that sees heat from the ship's power system (under 100km).

**Comment by zorkind** [comment]
I am not considering, i am set on it, you are opening suggestions based on things i have been discussing in Discord for a lot of time, i have been talking about this for way longer than the time you opened this suggestion.
