### ISSUE TITLE
Cutscene skipping breaks the game at character creation

### ISSUE THREAD

**Issue by Maverickwoe** [zorkind/Hellion-Rescue-Project#329]
**Vanilla / HRP**
HRP

**Client Version**
HRP Version ex.: 0.107

**Describe the bug**
When creating a new character on a server and selecting the second starting scenario (straight inside the haven), the message "press any key to continue" is shown indefinitely with sound of the cutscene but never goes to the game.
Game cannot be exited, it must be killed in task manager . Alt F4 won't work

**To Reproduce**
1. Create a new character
2. Select the second starting option from the top left
3. Skip the starting cutscene
4. Wait until you die or force quit the game

**Expected behavior**
The cutscene shall be skipped and we should be able to play

**Additional context**
Tried it on dedicated server as well as official EU server, same results

**Comment by GTink911** [comment]
Closed; please read the entirety of the Patch Notes before reporting any future bugs.
