### ISSUE TITLE
Warp plotting representation

### ISSUE THREAD

**Issue by Quarkof** [zorkind/Hellion-Rescue-Project#330]
**Is your feature request related to a problem? Please describe.**
No

When plotting a warp jump, the values of the distance and consumption indicate that from the time of travel timer you select how far the drop-out point will be from a longitudinal point of view relative to the destination.

However, the graphical representation indicates that you select the drop-out location on the orbit, although the longer you select the time, the farther the distance goes, even if it show's that you will be on the orbit in a closer position relative to the destination. 

A good idea would be to have a line that intersects the orbit. The time to destination should make the line shorter or longer until you intersect the orbit. Another box should select how fast will the travel be. 
The higher the speed, the higher the consumption after the initial base consumption in relation with distance.

**Comment by zorkind** [comment]
The orbital code is going to be replaced with a new one in 0.2.0 until then, I think the way it is represented is okish, I don't like the NavMap as it is and I will improve it, then we can discuss this again. :)
