### ISSUE TITLE
NCM

### ISSUE THREAD

**Issue by GDBlaster** [zorkind/Hellion-Rescue-Project#331]
**Is your feature request related to a problem? Please describe.**
annoying to change nanites on big bases

**Describe the solution you'd like**
Nanite center module module with lots of nanite core slots wich is sharing forcefield with the whole base (like the CBM to the external cargo container)

**Describe alternatives you've considered**
make all nanite cores common to the whole base but deplete faster (insted of s/Hazard have s/H/modules)

**Additional context**
no

**Comment by zorkind** [comment]
This idea was already thought about before, but the entire Nanite system is going to be reworked, and replaced.
