### ISSUE TITLE
ACM

### ISSUE THREAD

**Issue by GDBlaster** [zorkind/Hellion-Rescue-Project#332]
**Is your feature request related to a problem? Please describe.**
hard to keep track of items in the base

**Describe the solution you'd like**
Automatic cargo module like CBM but with a terminal that provides virtual storage for phisycal items

**Describe alternatives you've considered**
Null

**Additional context**
Null

**Comment by zorkind** [comment]
This is being discussed but not as a module, as a system that will be included in the existing modules.
