### ISSUE TITLE
Main/Auxiliary power systems

### ISSUE THREAD

**Issue by Quarkof** [zorkind/Hellion-Rescue-Project#334]
**Is your feature request related to a problem? .
No.

The power system on ships should be divided into:
Main power - Provides the same functions as the power switch does in the Vanilla game (except lights).

Aux power - Should enable RCS system, docking system, lights (including compartment labels), ability to pressurise/depressurize ship, gravity and open/close doors from buttons.

**Comment by zorkind** [comment]
Quarkof, these ideas are all already planned for 0.2.0

Please stop adding suggestions like these. I will keep closing them. :-\
