### ISSUE TITLE
Better self destruct 

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#35]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When you hit the self destruct module in a CM it blows up the entire base. Also a longer blow up animation with multiple explosions, similar to E:D. Don't kill the player until the final explosion.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
It already behaves like this, if cascades the explosion to near modules, i am not sure how many near modules it propagates to, tho.
