### ISSUE TITLE
Cargo Interaction Panel in the outside airlock of the CBM

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#46]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A CBM panel in the hallway outside the airlock.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
The title of this _really_ ought to be renamed so it doesn't sound like "opening the CBM doors from outside the CBM" because that's what the title makes me think when I read it.
