### ISSUE TITLE
when a bigger shelve is available instead of a small it will go yellow

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#50]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When a big shelve is available for a small item it looks yellow.

**Describe alternatives you've considered**
None.

**Additional context**
None.
also, make it so S/M/L letters for Small/Medium/Large shelves.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/103485457-4111f200-4dd5-11eb-9f16-22d376c54138.png)
