### ISSUE TITLE
Small cansisters on small shelves 

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#51]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Small canisters fit on small shelves.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GTink911** [comment]
Merged with #182.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/103485484-74ed1780-4dd5-11eb-9afb-5f678af1e6fe.png)
