### ISSUE TITLE
Door hack spot in Steropes

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#54]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A more obvious hacking spot in the Steropes.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
The current hacking spot in the Steropes is from the MK2 redesign, i don't see why change this, it's just about learning where it is in the new doors, if it's not on top of the lock, will always be on the "knoob" spot.

**Comment by zorkind** [comment]
The current hacking spot in the Steropes is from the MK2 redesign, i don't see why change this, it's just about learning where it is in the new doors, if it's not on top of the lock, will always be on the "knoob" spot.
