### ISSUE TITLE
Condense warp cells into a single warp cell.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#55]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
You can condense warp cells into a single warp cell. %5 loss.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
I remember a discussion with zg_smorty about the warp cells, and why they're not 'refillable'

IRL a car uses consumable materials - for example, brake pads. When they wear out, you replace them. You don't put more friction material on the pad.  You can't combine two worn-out sets of brake pads to make a new set. It's a consumable part - you replace it with a new part.

The warp cells are (according to lore) also a piece of hardware and certainly don't have some 'magic liquid' in them that can be transferred. 

Supposedly the cell contains Casmir sphere(s) to create the negative energy required to initialise the warp field; the 'fill level' of the cell is actually it's structural integrity. Near zero integrity = worn-out cell, time for a new one.

Warp cells are necessarily cheap, and recyclable. Personally I've never been keen on this suggestion and I'm hoping this project remains fairly faithful to the original and rejects suggestions that go against established lore, unless there's a _very_ good reason for it.

**Comment by zorkind** [comment]
This wont be necessary once the realtime cell consumption feature is added, specially for the Arges that uses more than one cell.

For the steropes, when the fuel runs out, you just swap the cell and the warp will continue IF you didn't move the ship, if you move it, the warp maneuver will be canceled and you will have to splot a new course.

Also, yes this means you can start warp maneuvers with partial warp cells, a warning will show up in the screen, making sure you know your current warp cell is not enough for the trip.

**Comment by GuiltyNeko** [comment]
The problem with simply exiting warp when fuel runs out and then automatically recommencing once there's a new warp cell is that the warp maneuver would have to be constantly recalculated for the current position.

**Comment by zorkind** [comment]
Like i explained, that recalculation will be automatic.
"the warp will continue IF you didn't move the ship, if you move it, the warp maneuver will be canceled and you will have to plot a new course."
