### ISSUE TITLE
Change usage of H3 as well as power output in fusion reactor

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#59]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
You can lower the power output from the fusion reactor, as well as the consumption of H3. This allows for not using unnecessary materials.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
This will happen in 0.2.0 when the system will be totally reworked. 👍
