### ISSUE TITLE
Steropes pilot seat, vision blocked by jetpack.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#6]
**Describe the bug**
When sitting in the pilot seat, you see the back of your suit and jetpack. Completely blocks vision. 
Only tested in Steropes and quick save/quick load fixes it 

**To Reproduce**
None

**Expected behavior**
Not having the vision blocked by the jetpack.

**Screenshots**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
This bug is related to the NetCode and it was caused by a different bug.

Already fixed.
