### ISSUE TITLE
Airlocks used as panic rooms.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#66]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Airlocks can always be pressurized if you have air in the tank. Also add a E-Signal, making it a sort of panic room. Add breach spots as well.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
I don't understand this at all, can you elaborate, rejecting for now.

**Comment by GTink911** [comment]
Currently the majority of rooms have breach spots, but airlocks do not. It would be nice to be able to pressurize the airlock even when the rooms surrounding it are depressurized, forming a type of panic room. While near useless currently, it could become quite helpful with the 0.2.0 damage rework.

**Comment by zorkind** [comment]
Well, we will see when we are working on 0.2.0 then 👍  i still don't see the use for this yet, because we will have ways to breach any door in the future, even secure ones, using torches and forcing our way thro.
