### ISSUE TITLE
T5 Nanite Core

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#76]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A T5 nanite core found in T4 zones. Has infinite protection, but only for a day.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
Sounds too much OP, i think T4 is good enough already. 

We can think this more if the need is really great.
