### ISSUE TITLE
Size scaling solar radiation damage

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#84]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Solar radiation gets higher with size. For example, a AM might have 1 radiation/s, while a OUTP has 2 radiation/s.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GTink911** [comment]
Personally don't like this idea.

**Comment by zorkind** [comment]
Radiation will be fully reworked for 0.2.0, making that kind of change now in 0.1.0 makes little sense.

The new radiation system from 0.2.0 can be implemented in 0.1.0 in the future.
