### ISSUE TITLE
Breach missile to punch holes in other ships during combat

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#86]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A launchable breach missile that causes breaches in enemy ships.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
This is something we will think about in 0.2.0, for now i will reject it.

We can fish this back from reject when 0.2.0 development starts.
