### ISSUE TITLE
More easily damagable solar panels

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#99]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Solar panels have way too much health. Have them break quicker after taking damage.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
They are super easy to break right now.

Also their health can be modified in server files, I THINK.

If not let me know here 👍
